language: ruby
rvm:
- 2.4.4
sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - oracle-java8-set-default

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.3.2.deb
  - sudo dpkg -i --force-confnew elasticsearch-6.3.2.deb
  - sudo service elasticsearch start

install:
  - travis_retry bundle install
  - curl -sL https://sentry.io/get-cli/ | bash
  - sentry-cli --version

before_script:
  - cp .env.travis .env

script:
  - bundle exec rspec

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - REPO=rorcommunity/ror-api;
  - AUTO_DEPLOY=false;
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker build -f Dockerfile -t $REPO .;
      docker push $REPO;
      echo "Pushed to" $REPO;
      AUTO_DEPLOY=true;
    elif [ "$TRAVIS_BRANCH" == "dev" ]; then
      docker build -f Dockerfile -t $REPO:$TRAVIS_BRANCH .;
      docker push $REPO:$TRAVIS_BRANCH;
      echo "Pushed to" $REPO:$TRAVIS_BRANCH;
      AUTO_DEPLOY=true;
    fi

  - if [ "$AUTO_DEPLOY" == "true" ]; then
      wget https://github.com/jwilder/dockerize/releases/download/v0.6.0/dockerize-linux-amd64-v0.6.0.tar.gz;
      tar -xzvf dockerize-linux-amd64-v0.6.0.tar.gz;
      rm dockerize-linux-amd64-v0.6.0.tar.gz;
      export GIT_SHA=$(git rev-parse --short HEAD);
      export GIT_TAG=$(git describe --tags $(git rev-list --tags --max-count=1));
      git clone "https://${TRAVIS_SECURE_TOKEN}@github.com/ror-community/deployment.git";
      
      sentry-cli releases new ror-api:${GIT_TAG} --finalize --project ror-api;
      
      if [ "$TRAVIS_BRANCH" == "master" ]; then
        ./dockerize -template vendor/docker/_ror-api.auto.tfvars.tmpl:deployment/ror/services/api/_ror-api.auto.tfvars;
        sentry-cli releases deploys ror-ap:${GIT_TAG} new -e production;
      else
        ./dockerize -template vendor/docker/_ror-api.auto.tfvars.tmpl:deployment/ror/services/api/_ror-api-dev.auto.tfvars;
        sentry-cli releases deploys ror-api:${GIT_TAG} new -e dev;
      fi

      sentry-cli releases set-commits --auto ror-api:${GIT_TAG};

      cd deployment;
      git remote;
      git config user.email ${DOCKER_EMAIL};
      git config user.name ${DOCKER_USERNAME};

      if [ "$TRAVIS_BRANCH" == "master" ]; then
        git add ror/services/api/_ror-api.auto.tfvars;
      elif [ "$TRAVIS_BRANCH" == "dev" ]; then
        git add ror/services/api/_ror-api-dv.auto.tfvars;
      fi

      git commit -m "Adding ror-api git variables for latest commit on branch $TRAVIS_BRANCH";
      git push "https://${TRAVIS_SECURE_TOKEN}@github.com/ror-community/deployment.git" master;
    fi

notifications:
  email: false
