language: python
python:
  - "3.6"

sudo: required

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.23.2

install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - cp .env.travis .env
  - docker-compose up -d
  - sleep 120
  - docker-compose exec web python manage.py setup

script:
  - docker-compose exec web python manage.py test rorapi.tests
  - docker-compose exec web python manage.py test rorapi.tests_integration
  - docker-compose exec web python manage.py test rorapi.tests_functional

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - REPO=rorcommunity/ror-api;
  - AUTO_DEPLOY=false;
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker build -f Dockerfile -t $REPO .;
      docker push $REPO;
      echo "Pushed to" $REPO;
      AUTO_DEPLOY=true;
    elif [ "$TRAVIS_BRANCH" == "dev" ]; then
      docker build -f Dockerfile -t $REPO:$TRAVIS_BRANCH .;
      docker push $REPO:$TRAVIS_BRANCH;
      echo "Pushed to" $REPO:$TRAVIS_BRANCH;
      AUTO_DEPLOY=true;
    fi

  - if [ "$AUTO_DEPLOY" == "true" ]; then
      wget https://github.com/jwilder/dockerize/releases/download/v0.6.0/dockerize-linux-amd64-v0.6.0.tar.gz;
      tar -xzvf dockerize-linux-amd64-v0.6.0.tar.gz;
      rm dockerize-linux-amd64-v0.6.0.tar.gz;
      export GIT_SHA=$(git rev-parse --short HEAD);
      export GIT_TAG=$(git describe --tags $(git rev-list --tags --max-count=1));
      git clone "https://${TRAVIS_SECURE_TOKEN}@github.com/ror-community/deployment.git";
      
      if [ "$TRAVIS_BRANCH" == "master" ]; then
        ./dockerize -template vendor/docker/_ror-api.auto.tfvars.tmpl:deployment/ror/services/api/_ror-api.auto.tfvars;
      elif [ "$TRAVIS_BRANCH" == "dev" ]; then
        ./dockerize -template vendor/docker/_ror-api.auto.tfvars.tmpl:deployment/ror/services/api/_ror-api-dev.auto.tfvars;
      fi
      
      cd deployment;
      git remote;
      git config user.email ${DOCKER_EMAIL};
      git config user.name ${DOCKER_USERNAME};

      if [ "$TRAVIS_BRANCH" == "master" ]; then
        git add ror/services/api/_ror-api.auto.tfvars;
      elif [ "$TRAVIS_BRANCH" == "dev" ]; then
        git add ror/services/api/_ror-api-dv.auto.tfvars;
      fi

      git commit -m "Adding ror-api git variables for latest commit on branch $TRAVIS_BRANCH";
      git push "https://${TRAVIS_SECURE_TOKEN}@github.com/ror-community/deployment.git" master;
    fi

notifications:
  email: false
