version: '3'

networks:
  orgid:
    external:
      name: orgid

services:
  elasticsearch:
    image: 'elasticsearch:5'
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    volumes:
      - [mount data dir]:/usr/share/elasticsearch/data
    networks:
      - orgid
  web:
    image: rorcommunity/org-id:initial_demo2
    networks:
      - orgid
    command: "bundle exec rackup --host 0.0.0.0 -p 3000"
    ports:
      - "9292:3000"
    environment:
      - ELASTIC_SEARCH=http://demo-ror_elasticsearch:9200
      - RACK_ENV=production
